modLoader = "javafml" #mandatory
loaderVersion = "${forge_loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "${license}"

[[mods]] #mandatory
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"

logoFile = "${mod_id}.png"
credits = "Deadlydiamond98, Nekomaster1000"
authors = "${mod_author}" #optional
description = '''Archery Expansion is a mod that adds new bow varients and mechanics to Minecraft

Credits:
Deadlydiamond98 - Developer
Nekomaster1000 - Artist, Designer
''' #mandatory (Supports multiline text)
[[dependencies.${mod_id}]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "AFTER" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
